
minetest.override_item("lb_api:lucky_block", {
	tiles = {"lucky_block.png"},
	inventory_image = minetest.inventorycube("lucky_block.png")
})

minetest.override_item("lb_api:super_lucky_block", {
	tiles = {"lucky_block.png"},
	inventory_image = minetest.inventorycube("lucky_block.png")
})

lb_api:purge_block_list()

lb_api:use_default_schematics(4)

lb_api:add_chest_items({
	{name = "default:apple", max = 3},
	{name = "default:steel_ingot", max = 2},
	{name = "default:gold_ingot", max = 2},
	{name = "default:diamond", max = 1},
	{name = "default:pick_steel", max = 1}
})

lb_api:add_blocks({
	{"tel"},
	{"lig"},
	{"exp"},
	{"dro", {"xdecor:enchantment_table"}, 1},
	{"dro", {"xdecor:hammer"}, 1},
	{"nod", "xdecor:worktable", 0},
	{"tro", "xdecor:worktable", nil, true},
	{"lig"},
	{"exp"},
	{"dro", {"walking_light:pick_mese"}, 1},
	{"lig"},
	{"exp"},
	{"dro", {"throwing:arbalest_auto"}, 1},
	{"dro", {"throwing:arrow_diamond"}, 10},
	{"dro", {"throwing:spear_diamond"}, 2},
	{"lig"},
	{"exp"},
	{"dro", {"teleport_potion:potion"}, 1},
	{"lig"},
	{"exp"},
	{"dro", {"pie:"}, 4},
	{"tro", "pie:", nil, true},
	{"lig"},
	{"exp"},
	{"nod", "moreores:mithril_block", 0},
	{"tro", "moreores:mithril_block", nil, true},
	{"dro", {"moreores:mithril_ingot"}, 5},
	{"dro", {"moreores:mithril_sword", "moreores:mithril_pick", "moreores:mithril_axe", "moreores:mithril_shovel", "moreores:mithril_hoe"}, 5},
	{"lig"},
	{"exp"},
	{"spw", "mobs_turtles:turtle", 3},
	{"spw", "mobs_crocs:crocodile", 5},
	{"spw", "mobs_butterfly:butterfly", 8},
	{"spw", "mobs_bat:bat", 6},
	{"spw", "mobs_zombie:zombie", 4},
	{"spw", "mobs_slimes:green_big", 2},
	{"spw", "mobs_slimes:lava_big", 2},
	{"spw", "mobs_sandworm:sandworm", 1},
	{"dro", {"mobs_sandworm:spice"}, 1},
	{"spw", "mobs_pumpking:pumpking", 1},
	{"spw", "mobs_creeper:creeper", 2},
	{"spw", "mobs_wolf:dog", 3},
	{"spw", "mobs_bear:medved", 2},
	{"spw", "mobs:sheep", 5},
	{"spw", "mobs:dungeon_master", 1},
	{"spw", "mobs:sand_monster", 3},
	{"spw", "mobs:stone_monster", 3},
	{"spw", "mobs:bunny", 3},
	{"spw", "mobs:spider", 5},
	{"spw", "mobs:pumba", 5},
	{"spw", "mobs:mese_monster", 2},
	{"spw", "mobs:chicken", 5},
	{"spw", "mobs:lava_flan", 3},
	{"spw", "mobs:cow", 5},
	{"spw", "mobs:kitten", 2},
	{"spw", "mobs:rat", 5},
	{"spw", "mobs:dirt_monster", 3},
	{"spw", "mobs:tree_monster", 3},
	{"spw", "mobs:oerkki", 3},
	{"dro", {"mobs:rat_cooked"}, 5},
	{"dro", {"mobs:meat_raw"}, 5},
	{"dro", {"mobs:meat"}, 5},
	{"dro", {"mobs:egg"}, 10},
	{"dro", {"mobs:bucket_milk"}, 10},
	{"dro", {"mobs:leather"}, 6},
	{"nod", "mobs:honey_block", 0},
	{"nod", "mobs:cheeseblock", 0},
	{"nod", "mobs:beehive", 0},
	{"nod", "default:chest", 0, {{name = "mobs:lava_orb", max = 1}}},
	{"tro", "mobs:honey_block", nil, true},
	{"tro", "mobs:cheeseblock", nil, true},
	{"tro", "default:nyancat", "mobs_kitten", true},
	{"tro", "mobs:beehive", nil, true},
	{"lig"},
	{"exp"},
	{"dro", {"blox:"}, 8},
	{"lig"},
	{"exp"},
	{"dro", {"3d_armor:boots_diamond", "3d_armor:leggings_diamond", "3d_armor:chestplate_diamond", "3d_armor:helmet_diamond", "shields:shield_diamond"}, 3},
	{"dro", {"3d_armor:boots_crystal", "3d_armor:leggings_crystal", "3d_armor:chestplate_crystal", "3d_armor:helmet_crystal", "shields:shield_crystal"}, 3},
	{"dro", {"3d_armor:boots_wood", "3d_armor:leggings_wood", "3d_armor:chestplate_wood", "3d_armor:helmet_wood", "shields:shield_wood"}, 3},
	{"dro", {"3d_armor:boots_steel", "3d_armor:leggings_steel", "3d_armor:chestplate_steel", "3d_armor:helmet_steel", "shields:shield_steel"}, 3},
	{"dro", {"3d_armor:boots_gold", "3d_armor:leggings_gold", "3d_armor:chestplate_gold", "3d_armor:helmet_gold", "shields:shield_gold"}, 3},
	{"dro", {"3d_armor:boots_cactus", "3d_armor:leggings_cactus", "3d_armor:chestplate_cactus", "3d_armor:helmet_cactus", "shields:shield_cactus"}, 3},
	{"dro", {"3d_armor:boots_bronze", "3d_armor:leggings_bronze", "3d_armor:chestplate_bronze", "3d_armor:helmet_bronze", "shields:shield_bronze"}, 3},
	{"dro", {"3d_armor:boots_mithril", "3d_armor:leggings_mithril", "3d_armor:chestplate_mithril", "3d_armor:helmet_mithril", "shields:shield_mithril"}, 3},
	{"lig"},
	{"exp"},
	{"nod", "fire:basic_flame", 1},
	{"lig"},
	{"exp"},
	{"dro", {"farming:bread"}, 5},
	{"lig"},
	{"exp"},
	{"dro", {"wool:"}, 10, true},
	{"lig"},
	{"exp"},
	{"dro", {"default:torch"}, 10},
	{"dro", {"default:apple"}, 10},
	{"dro", {"default:snow"}, 10},
	{"dro", {"default:mese_crystal_fragment", "default:mese_crystal"}, 10},
	{"nod", "default:diamondblock", 0},
	{"tro", "default:diamondblock", nil, true},
	{"nod", "default:steelblock", 0},
	{"tro", "default:steelblock", nil, true},
	{"nod", "default:ironblock", 0},
	{"tro", "default:ironblock", nil, true},
	{"nod", "default:dirt", 0},
	{"tro", "default:dirt", nil, true},
	{"dro", {"default:coal_lump"}, 3},
	{"nod", "default:wood", 0},
	{"tro", "default:wood", nil, true},
	{"nod", "default:gravel", 0},
	{"tro", "default:gravel", nil, true},
	{"dro", {"default:diamond"}, 8},
	{"dro", {"default:sword_steel", "default:pick_steel", "default:shovel_steel", "default:axe_steel"}, 1},
	{"dro", {"default:sword_bronze", "default:pick_bronze", "default:shovel_bronze", "default:axe_bronze"}, 1},
	{"dro", {"default:sword_diamond", "default:pick_diamond", "default:shovel_diamond", "default:axe_diamond"}, 1},
	{"lig"},
	{"exp"},
	{"fal", {"default:wood", "default:gravel", "default:sand", "default:desert_sand", "default:stone", "default:dirt", "default:goldblock"}, 0},
	{"fal", {"default:ironblock", "default:ironblock", "default:ironblock"}, 0},
	{"fal", {"default:diamondblock", "default:diamondblock", "default:diamondblock"}, 0},
	{"fal", {"moreores:mithril_block", "moreores:mithril_block", "moreores:mithril_block"}, 0},
	{"fal", {"default:sword_steel", "moreores:mithril_block", "default:diamondblock", "default:ironblock", "default:goldblock", }, 0},
	{"nod", "default:chest", 0, {
		{name = "bucket:bucket_water", max = 1},
		{name = "default:wood", max = 3},
		{name = "default:pick_diamond", max = 1},
		{name = "default:coal_lump", max = 3}}},
})

if farming.mod and farming.mod == "redo" then
	lb_api:add_blocks({
		{"dro", {"farming:corn"}, 5},
		{"dro", {"farming:coffee_cup_hot"}, 1},
		{"dro", {"farming:bread"}, 5},
		{"nod", "farming:jackolantern", 0},
		{"tro", "farming:jackolantern", nil, true},
		{"nod", "farming:melon", 0},
		{"tro", "farming:melon", nil, true},
		{"dro", {"farming:donut", "farming:donut_chocolate", "farming:donut_apple"}, 5}
	})
end
